namespace WadMaker.Models;

public enum ThingType
{
    Unknown = 0,
    Player1_start = 1,
    Player_2_start = 2,
    Player_3_start = 3,
    Player_4_start = 4,
    Blue_keycard = 5,
    Yellow_keycard = 6,
    Spiderdemon = 7,
    Backpack = 8,
    Shotgun_guy = 9,
    Bloody_mess = 10,
    Deathmatch_start = 11,
    Bloody_mess = 12,
    Red_keycard = 13,
    Teleportlanding = 14,
    Dead_player = 15,
    Cyberdemon = 16,
    Energy_cell_pack = 17,
    Dead_former_human = 18,
    Dead_former_sergeant = 19,
    Dead_imp = 20,
    Dead_demon = 21,
    Dead_cacodemon = 22,
    Dead_lost_soul_invisible = 23,
    Pool_of_blood_and_flesh = 24,
    Impaled_human = 25,
    Twitching_impaled_human = 26,
    Skull_on_a_pole = 27,
    Five_skulls_shish_kebab = 28,
    Pile_of_skulls_and_candles = 29,
    Tall_green_pillar = 30,
    Short_green_pillar = 31,
    Tall_red_pillar = 32,
    Short_red_pillar = 33,
    Candle = 34,
    Candelabra = 35,
    Short_green_pillar_with_beating_heart = 36,
    Short_red_pillar_with_skull = 37,
    Red_skull_key = 38,
    Yellow_skull_key = 39,
    Blue_skull_key = 40,
    Evil_eye = 41,
    Floating_skull = 42,
    Burnt_tree = 43,
    Tall_blue_firestick = 44,
    Tall_green_firestick = 45,
    Tall_red_firestick = 46,
    Brown_stump = 47,
    Tall_techno_column = 48,
    Hanging_victim_twitching = 49,
    Hanging_victim_arms_out = 50,
    Hanging_victim_onelegged = 51,
    Hanging_pair_of_legs = 52,
    Hanging_leg = 53,
    Large_brown_tree = 54,
    Short_blue_firestick = 55,
    Short_green_firestick = 56,
    Short_red_firestick = 57,
    Spectre = 58,
    Hanging_victim_arms_out = 59,
    Hanging_pair_of_legs = 60,
    Hanging_victim_onelegged = 61,
    Hanging_leg = 62,
    Hanging_victim_twitching = 63,
    Archvile = 64,
    Heavy_weapon_dude = 65,
    Revenant = 66,
    Mancubus = 67,
    Arachnotron = 68,
    Hell_knight = 69,
    Burning_barrel = 70,
    Pain_elemental = 71,
    Commander_Keen = 72,
    Hanging_victim_guts_removed = 73,
    Hanging_victim_guts_and_brain_removed = 74,
    Hanging_torso_looking_down = 75,
    Hanging_torso_open_skull = 76,
    Hanging_torso_looking_up = 77,
    Hanging_torso_brain_removed = 78,
    Pool_of_blood = 79,
    Pool_of_blood = 80,
    Pool_of_brains = 81,
    Super_shotgun = 82,
    Megasphere = 83,
    Wolfenstein_SS = 84,
    Tall_techno_floor_lamp = 85,
    Short_techno_floor_lamp = 86,
    Spawn_spot = 87,
    Romeros_head = 88,
    Monster_spawner = 89,
    Shotgun = 2001,
    Chaingun = 2002,
    Rocket_launcher = 2003,
    Plasma_gun = 2004,
    Chainsaw = 2005,
    BFG9000 = 2006,
    Clip = 2007,
    4_shotgun_shells = 2008,
    Rocket = 2010,
    Stimpack = 2011,
    Medikit = 2012,
    Supercharge = 2013,
    Health_bonus = 2014,
    Armor_bonus = 2015,
    Armorgreen = 2018,
    Megaarmorblue = 2019,
    Invulnerability = 2022,
    Berserk = 2023,
    Partial_invisibility = 2024,
    Radiation_shielding_suit = 2025,
    Computer_area_map = 2026,
    Floor_lamp = 2028,
    Exploding_barrel = 2035,
    Light_amplification_visor = 2045,
    Box_of_rockets = 2046,
    Energy_cell = 2047,
    Box_of_bullets = 2048,
    Box_of_shotgun_shells = 2049,
    Imp = 3001,
    Demon = 3002,
    Baron_of_Hell = 3003,
    Zombieman = 3004,
    Cacodemon = 3005,
    Lost_soul = 3006
}


public enum ThingCategory
{
  Other,
  Weapon,
  Ammo,
  Monster
}

[Flags]
public enum ThingFlags
{
  None = 0,
  Skill1 = 1,
  Skill2 = 2,
  Skill3 = 4,
  Skill4 = 8,
  Skill5 = 16,
  Single = 32,
  Deathmatch = 64,
  CoOp = 128,
  Ambush = 256,
  AllSkills = Skill1 + Skill2 + Skill3 + Skill4 + Skill5,
  AllModes = Single + Deathmatch + CoOp,
}

public record DoomThingInfo(int Decimal, string Hex, string Version, int Radius, int Height,
  string Sprite, string Sequence, string Class, string Description);